#terminal
bindsym $mod+Return exec $term

# Kill
bindsym $mod+q kill

# Launcher
bindsym $mod+Space exec $menu

# Recarrega .conf
bindsym $mod+c

# Screenshot
bindsym $mod+Shift+s exec grim


bindsym $mod+m mode "Move"
bindsym $mod+r mode "Resize"
bindsym $mod+w mode "Workspace"



#####################################################################
## Audio
#####################################################################

# PulseAudio
bindsym --locked XF86AudioMute exec pactl set-sink-mute \@DEFAULT_SINK@ toggle
bindsym --locked XF86AudioLowerVolume exec pactl set-sink-volume \@DEFAULT_SINK@ -5%
bindsym --locked XF86AudioRaiseVolume exec pactl set-sink-volume \@DEFAULT_SINK@ +5%
bindsym --locked XF86AudioMicMute exec pactl set-source-mute \@DEFAULT_SOURCE@ toggle

# brightnessctl
bindsym --locked XF86MonBrightnessDown exec brightnessctl set 5%-
bindsym --locked XF86MonBrightnessUp exec brightnessctl set 5%+


#####################################################################
## Janelas e Workspace
#####################################################################

# Janelas
    # Variaveis
    bindsym $mod+$up focus up
    bindsym $mod+$right focus right
    bindsym $mod+$down focus down
    bindsym $mod+$left focus left
    
    # Setas
    bindsym $mod+Up focus up
    bindsym $mod+Right focus right
    bindsym $mod+Down focus down
    bindsym $mod+Left focus left



# Workspace
    # Variaveis
    bindsym $mod+Shift+$right workspace next
    bindsym $mod+Shift+$left workspace prev

    # Setas
    bindsym $mod+Shift+right workspace next
    bindsym $mod+Shift+left workspace prev
    
    bindsym $mod+1 workspace $w1
    bindsym $mod+2 workspace $w2
    bindsym $mod+3 workspace $w3
    bindsym $mod+4 workspace $w4
    bindsym $mod+5 workspace $w5
    bindsym $mod+6 workspace $w6
    bindsym $mod+7 workspace $w7
    bindsym $mod+8 workspace $w8
    bindsym $mod+9 workspace $w9
    bindsym $mod+0 workspace $w10



#####################################################################
## Modos
#####################################################################

mode "Move"
{
    # Variaveis
    bindsym $up move up
    bindsym $right move right
    bindsym $left move left
    bindsym $down move down
    
    # Setas
    bindsym Up move up
    bindsym Right move right
    bindsym Down move down
    bindsym Left move left
    
    bindsym $mod+m mode "default"
    bindsym return mode "default"
    bindsym scape mode "default"
}



mode: "Resize"
{
    # Variaveisc
    bindsym $up resize grow height 10px
    bindsym $right resize grow width 10px
    bindsym $down resize shrink height 10px
    bindsym $left resize shrink width 10px
    
    # Setas
    bindsym up resize grow height 10px
    bindsym right resize grow width 10p
    bindsym down resize shrink height 10px
    bindsym left resize shrink width 10px
    
    bindsym $mod+r mode "default"
    bindsym return mode "default"
    bindsym scape mode "default"
}



mode "Workspace"
{
    bindsym $mod+1 [workspace=".*"] move to workspace $w1; workspace $w1, mode "default"
    bindsym $mod+2 [workspace=".*"] move to workspace $w2; workspace $w2, mode "default"
    bindsym $mod+3 [workspace=".*"] move to workspace $w3; workspace $w3, mode "default"
    bindsym $mod+4 [workspace=".*"] move to workspace $w4; workspace $w4, mode "default"
    bindsym $mod+5 [workspace=".*"] move to workspace $w5; workspace $w5, mode "default"
    bindsym $mod+6 [workspace=".*"] move to workspace $w6; workspace $w6, mode "default"
    bindsym $mod+7 [workspace=".*"] move to workspace $w7; workspace $w7, mode "default"
    bindsym $mod+8 [workspace=".*"] move to workspace $w8; workspace $w8, mode "default"
    bindsym $mod+9 [workspace=".*"] move to workspace $w9; workspace $w9, mode "default"
    bindsym $mod+0 [workspace=".*"] move to workspace $w10; workspace $w10, mode "default"
    
    bindsym $mod+w mode "default"
    bindsym return mode "default"
    bindsym scape mode "default"
}
